baseURL = 'http://goforaditya.github.io/letstry'
languageCode = 'en-us'
title = 'Lets Try'
theme = 'mainroad'
menu = 'main'

[Author] # Used in authorbox
  name = "@goforaditya"
  bio = "Tech Enthusiast trying to become a techpreneur."
  avatar = "img/avatar1.png"

[Params]
  description = "Trying to learn technologies." # Site description. Used in meta description
  copyright = "@goforaditya" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  mainSections = ["blog"]
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  dateformat = "2006-01-02" # Change the format of dates

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist", "social"]

[Params.logo]
  image = "img/letstrylogo.png" # Logo image. Path relative to "static"
  title = "Learning new tech" # Logo title, otherwise will use site title
  subtitle = "Documenting the journey" # Logo subtitle

[Params.widgets.social]
  github = "goforaditya"

[menu]
[[menu.main]]
  name = 'blog'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/blog/'
  weight = -100
[[menu.main]]
  identifier = 'diary'
  name = 'diary'
  pre = "<i class='fa fa-heart'></i>"
  url = '/diary/'
  weight = -110